# Generated by Django 4.2.5 on 2023-09-24 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_result_student_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.FloatField()),
                ('outstanding', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.course')),
                ('student_code', models.ForeignKey(db_column='student_code', on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
