# Generated by Django 4.2.5 on 2023-09-24 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_fees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_fees',
            name='outstanding',
        ),
    ]
