# Generated by Django 4.2.5 on 2023-09-24 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_student_fees_outstanding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_fees',
            name='course',
        ),
    ]
