# Generated by Django 4.2.5 on 2023-09-30 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_student_fees_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_fees',
            name='student_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
